### ISSUE TITLE
Add interactive example

### ISSUE THREAD

**Issue by adrhill** [JuliaImages/DitherPunk.jl#17]
Host a Pluto notebook using DitherPunk on Binder using https://pluto-on-binder.glitch.me.
This can then be linked to from the readme and docs.

## Feature checklist
- [x] option to select image from file or URL
- [x] sliders to rescale image
- [x] dropdown menu to select dithering algorithm

**Comment by adrhill** [comment]
Sadly, loading [this notebook](https://github.com/JuliaImages/DitherPunk.jl/blob/adrhill/pluto-demo/docs/pluto/demo.jl) takes too long on Binder... :(

**Comment by johnnychen94** [comment]
Maybe use `ImageShow.gif` with plain documents? I like this function very much https://github.com/JuliaImages/juliaimages.github.io/pull/191

**Comment by adrhill** [comment]
DitherPunk is now a [featured Pluto notebook](https://featured.plutojl.org/puzzles-games/dither.html)!
<img width="1010" alt="image" src="https://github.com/user-attachments/assets/0670132d-f608-4987-89db-9fed4fe05f88">
