### ISSUE TITLE
store the color result using IndirectArrays

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/DitherPunk.jl#28]
Since the dithered colorful image only uses very few distinctive values, it's intuitive to just store and process them in index image format (`IndirectArray`). That further compresses the memory but I'm not sure yet how this affects the performance.

**Comment by adrhill** [comment]
Would you just use an `IndirectArray` before or after applying the dithering algorithm?

**Comment by johnnychen94** [comment]
I think it's making the output of the dithering algorithm an `IndirectArray`, and let the consumers of `dither` decide whether they need a `collect`. For fixed color dither this should save a bunch of memory I believe.

**Comment by adrhill** [comment]
Sounds good! If a regular array is passed to `dither!`, should it be turned into an `IndirectArray` too?

This is also a good excuse to add #35. ;)

**Comment by johnnychen94** [comment]
> If a regular array is passed to dither!, should it be turned into an IndirectArray too?

Oh for this you simply can't, because if you create a new array `out` for `dither!(out, img)`, then it's a different memory.

```julia
function f!(out, src)
    out = zeros(4, 4)
    out .= src
    return out # this `out` is not the outside `out`
end

out = zeros(4, 4);
src = rand(4, 4);
f!(out, src)
out == src # false
```
