### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by Tinkerer-Zlosk** [JuliaImages/DitherPunk.jl#30]
https://github.com/JuliaImages/DitherPunk.jl/blob/8f598de9ca59361a2af22147d3c2fc39d4281536/src/dither_api.jl#L67

The 'dither' function lists 'binarize' as the function name in the documentation.

**Comment by Tinkerer-Zlosk** [comment]
Sure.

**Comment by adrhill** [comment]
Closed by #31.
