### ISSUE TITLE
Add images to readme

### ISSUE THREAD

**Issue by adrhill** [JuliaImages/DitherPunk.jl#33]
The readme refers to the gallery in the docs but looks a bit dry. 
Should I add an asset-folder to `/docs` or just upload some images as comments here and link to them @johnnychen94?

**Comment by johnnychen94** [comment]
Adding an asset folder to `docs/` definitely works, there is just one small thing: Julia Pkg Server will achieve everything in the `master` branch and ship them to the users. So if you're planning to add like 10M files, that would be a large burden. An extreme case like this is https://github.com/tlnagy/OMETIFF.jl/issues/87

Upload images as comments here is a trick to work around this limitation. So I think it's probably a better option. But of course, need some more manual work if you plan to upload tens of images.

Another option is to have them in `gh-pages` branch and then use raw link here, e.g.,

```html
the rawlink to https://github.com/JuliaImages/juliaimages.github.io/blob/master/dev/examples/color_channels/assets/indexed_image.png
![](https://raw.githubusercontent.com/JuliaImages/juliaimages.github.io/master/dev/examples/color_channels/assets/indexed_image.png)
<img src="https://raw.githubusercontent.com/JuliaImages/juliaimages.github.io/master/dev/examples/color_channels/assets/indexed_image.png" alt="bad_result.png" width="100">
```

<img src="https://raw.githubusercontent.com/JuliaImages/juliaimages.github.io/master/dev/examples/color_channels/assets/indexed_image.png" alt="bad_result.png" width="100">
